version: '3.6'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.0.0
    volumes:
      - /data/elasticsearch/data:/usr/share/elasticsearch/data
      - /data/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - TZ=Asia/Shanghai
      - node.name=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
