version: '3.5'
services:
  jenkins:
    image: jenkins:2.164.3
    container_name: jenkins2.164.3
    restart: always
    environment:
       - TZ=Asia/Shanghai
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /data/jenkins_home:/var/jenkins_home
    ports:
       - 50000:50000
       - 8080:8080
